name = "gchi-website"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "gchi-database"
database_id = "YOUR_DATABASE_ID" # Will be set after creation

# KV Namespace for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "YOUR_KV_NAMESPACE_ID" # Will be set after creation

# Queue for email jobs
[[queues.producers]]
binding = "EMAIL_QUEUE"
queue = "email-queue"

[[queues.consumers]]
queue = "email-queue"
max_batch_size = 10
max_batch_timeout = 30

# R2 Storage for PDFs
[[r2_buckets]]
binding = "DOCUMENTS"
bucket_name = "gchi-documents"

# Environment variables (add these to Cloudflare dashboard)
[vars]
NODE_ENV = "production"

# Development settings
[env.development]
vars = { NODE_ENV = "development" }

# Production settings  
[env.production]
vars = { NODE_ENV = "production" }
