name = "goldencanadianhomes"
main = ".vercel/output/static/_worker.js"
compatibility_date = "2025-08-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:next && npx @cloudflare/next-on-pages"

[assets]
directory = ".vercel/output/static"
# Exclude worker files from assets
ignore = ["_worker.js"]

# D1 Database binding (optional - uncomment when needed)
# [[d1_databases]]
# binding = "DB"
# database_name = "gchi-database"
# database_id = "YOUR_DATABASE_ID"

# KV Namespace for rate limiting (optional - uncomment when needed)
# [[kv_namespaces]]
# binding = "RATE_LIMIT_KV"
# id = "YOUR_KV_NAMESPACE_ID"

# R2 Storage for PDFs (optional - uncomment when needed)
# [[r2_buckets]]
# binding = "DOCUMENTS"
# bucket_name = "gchi-documents"

# Queue for email jobs (optional - uncomment when needed)
# [[queues.producers]]
# binding = "EMAIL_QUEUE"
# queue = "email-queue"

# Environment variables (set these in Cloudflare dashboard or as secrets)
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "http://localhost:8787"

# Preview settings (for branch deployments)
[env.preview.vars]
NODE_ENV = "preview"
NEXT_PUBLIC_APP_URL = "http://localhost:8787"

# Production settings  
[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_APP_URL = "https://goldencanadianhomes.ca"

# Production KV bindings (uncomment when created)
# [[env.production.kv_namespaces]]
# binding = "RATE_LIMIT_KV"
# id = "YOUR_PROD_KV_NAMESPACE_ID"
