name: Deploy to Cloudflare Pages

on:
  # Triggers on push to main branch
  push:
    branches:
      - main
  # Allows manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    
    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Build the Next.js application
      - name: Build Next.js
        run: npm run build
        env:
          # Add any build-time environment variables here
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL || 'https://gchi-website.pages.dev' }}

      # Build for Cloudflare Workers
      - name: Build for Cloudflare Workers
        run: npx @cloudflare/next-on-pages

      # Deploy to Cloudflare Workers
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy
