name: Deploy Preview

on:
  # Triggers on pull requests
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Deploy Preview to Cloudflare Pages
    
    steps:
      # Checkout the PR code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Build the Next.js application
      - name: Build Next.js
        run: npm run build
        env:
          # Preview environment variables
          NEXT_PUBLIC_SITE_URL: https://preview.gchi-website.pages.dev

      # Build for Cloudflare Workers
      - name: Build for Cloudflare Workers
        run: npx @cloudflare/next-on-pages

      # Deploy preview to Cloudflare Workers
      - name: Deploy Preview to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env preview

      # Preview deployment success
      - name: Preview Deployment Success
        run: |
          echo "🚀 Preview deployment complete!"
          echo "Preview URL will be available at your Workers subdomain"
