name: Deploy Preview

on:
  # Triggers on pull requests
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Deploy Preview to Cloudflare Pages
    
    steps:
      # Checkout the PR code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Build for Cloudflare (Next.js + Workers)
      - name: Build for Cloudflare
        run: npm run build:full
        env:
          # Preview environment variables
          NEXT_PUBLIC_APP_URL: 'https://preview.goldencanadianhomes.ca'

      # Deploy preview to Cloudflare Workers
      - name: Deploy Preview to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy .vercel/output/static

      # Preview deployment success
      - name: Preview Deployment Success
        run: |
          echo "🚀 Preview deployment complete!"
          echo "Preview URL will be available at your Workers subdomain"
