name: Deploy Preview

on:
  # Triggers on pull requests
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Deploy Preview to Cloudflare Pages
    
    steps:
      # Checkout the PR code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Build the Next.js application
      - name: Build Next.js
        run: npm run build
        env:
          # Preview environment variables
          NEXT_PUBLIC_SITE_URL: https://preview.gchi-website.pages.dev

      # Build for Cloudflare using Vercel output
      - name: Build for Cloudflare
        run: |
          npx vercel build --prod --local-config=vercel-build.json
          npx @cloudflare/next-on-pages --skip-build

      # Deploy preview to Cloudflare Pages
      - name: Deploy Preview to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: gchi-website
          directory: .vercel/output/static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Deploy to preview branch
          branch: preview-${{ github.event.pull_request.number }}

      # Comment on PR with preview URL
      - name: Comment Preview URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const previewUrl = `https://preview-${prNumber}.gchi-website.pages.dev`;
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `🚀 Preview deployed to: ${previewUrl}`
            });
