name: Deploy Preview

on:
  # Triggers on pull requests
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    name: Deploy Preview to Cloudflare Pages
    
    steps:
      # Checkout the PR code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Build the Next.js application
      - name: Build Next.js
        run: npm run build
        env:
          # Preview environment variables
          NEXT_PUBLIC_SITE_URL: https://preview.gchi-website.pages.dev

      # Build for Cloudflare Pages
      - name: Build for Cloudflare
        run: npx @cloudflare/next-on-pages

      # Deploy preview to Cloudflare Pages
      - name: Deploy Preview to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: gchi-website
          directory: .vercel/output/static
          # Deploy to preview branch
          branch: preview-${{ github.event.pull_request.number }}

      # Preview URL will be available at: https://preview-{PR-NUMBER}.gchi-website.pages.dev
      - name: Preview Deployment Success
        run: |
          echo "🚀 Preview deployment complete!"
          echo "Preview URL: https://preview-${{ github.event.pull_request.number }}.gchi-website.pages.dev"
